## **Part B: Dataset Understanding & Preparation**

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('dataset/students_dataset.csv')

In [3]:
data.columns

Index(['student_id', 'age', 'country_region', 'device_type',
       'education_background', 'course_level', 'course_category',
       'course_start_date', 'week_of_year', 'sessions', 'time_spent_hours',
       'videos_watched', 'quiz_attempts', 'assignments_submitted',
       'forum_posts', 'avg_quiz_score', 'attendance_rate', 'completion_status',
       'final_score'],
      dtype='object')

### Task 6: Feature & Target Identification

In [4]:
X = data.drop(columns=['student_id','age','device_type','course_start_date'])

In [5]:
y_cls = data.completion_status

In [6]:
y_reg = data.final_score

### Tasl 8: Data Preprocessing

In [7]:
from sklearn.preprocessing import OrdinalEncoder

In [8]:
# data before preprocessing
X.head()

,country_region,education_background,course_level,course_category,week_of_year,sessions,time_spent_hours,videos_watched,quiz_attempts,assignments_submitted,forum_posts,avg_quiz_score,attendance_rate,completion_status,final_score
0,Europe,Undergrad,Intermediate,Business,12,1,7.6,1,6,1,1,53.3,0.655,0,49.8
1,Europe,Undergrad,Intermediate,Programming,34,16,27.2,6,4,7,1,51.5,1.000,1,84.0
2,Europe,Graduate,Advanced,Programming,39,6,7.1,16,2,2,0,62.2,0.810,0,62.5
3,Asia,Undergrad,Beginner,Design,10,34,22.1,57,9,6,0,59.3,0.875,1,89.5
4,Asia,WorkingPro,Advanced,Business,12,22,32.3,41,9,2,0,65.1,0.814,0,67.4

In [9]:
# Cheacking missing values
X.isna().sum()

country_region             0
education_background       0
course_level               0
course_category            0
week_of_year               0
sessions                   0
time_spent_hours         112
videos_watched             0
quiz_attempts              0
assignments_submitted      0
forum_posts                0
avg_quiz_score            81
attendance_rate           80
completion_status          0
final_score                0
dtype: int64

In [10]:
# Filling missing values with 0
X.fillna(0,inplace=True)

In [11]:
# Cheacking Datatypes
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5200 entries, 0 to 5199
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   country_region         5200 non-null   object
 1   education_background   5200 non-null   object
 2   course_level           5200 non-null   object
 3   course_category        5200 non-null   object
 4   week_of_year           5200 non-null   int64
 5   sessions               5200 non-null   int64
 6   time_spent_hours       5200 non-null   float64
 7   videos_watched         5200 non-null   int64
 8   quiz_attempts          5200 non-null   int64
 9   assignments_submitted  5200 non-null   int64
 10  forum_posts            5200 non-null   int64
 11  avg_quiz_score         5200 non-null   float64
 12  attendance_rate        5200 non-null   float64
 13  completion_status      5200 non-null   int64
 14  final_score            5200 non-null   float64
dtypes: float64(4), int64(7), object(4)
memory usage: 609.5+ KB

In [12]:
# Making variables for Encoder with and without order

education = ['HighSchool','Undergrad','Graduate','WorkingPro']
course_lvl = ['Beginner','Intermediate','Advanced']
country = X['country_region'].unique()
course_cat = X['course_category'].unique()

In [13]:
# Using Ordinal Encoder for Encoding Categorical features
OE = OrdinalEncoder(
    categories=[education,course_lvl,country,course_cat]
)

In [14]:
# Replacing values to categorical to numeric
X[['education_background','course_level','country_region','course_category']] = OE.fit_transform(X[['education_background','course_level','country_region','course_category']])

In [15]:
# Data Overview after Preprocessing
X.head()

,country_region,education_background,course_level,course_category,week_of_year,sessions,time_spent_hours,videos_watched,quiz_attempts,assignments_submitted,forum_posts,avg_quiz_score,attendance_rate,completion_status,final_score
0,0.0,1.0,1.0,0.0,12,1,7.6,1,6,1,1,53.3,0.655,0,49.8
1,0.0,1.0,1.0,1.0,34,16,27.2,6,4,7,1,51.5,1.000,1,84.0
2,0.0,2.0,2.0,1.0,39,6,7.1,16,2,2,0,62.2,0.810,0,62.5
3,1.0,1.0,0.0,2.0,10,34,22.1,57,9,6,0,59.3,0.875,1,89.5
4,1.0,3.0,2.0,0.0,12,22,32.3,41,9,2,0,65.1,0.814,0,67.4

### Task 7: Train-Test Split

In [16]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [26]:
# Train-Test-Split for Regression 
X_train_reg,X_test_reg,y_train_reg,y_test_reg = train_test_split(X,y_reg,test_size=0.2,random_state=42)

In [27]:
# Train-Test-Split for Classification 
X_train_cls,X_test_cls,y_train_cls,y_test_cls = train_test_split(X,y_cls,test_size=0.2,random_state=42)

## **Part C: Bagging (Bootstrap Aggregation)**

In [24]:
from sklearn.ensemble import BaggingClassifier,BaggingRegressor
from sklearn.tree import DecisionTreeClassifier,DecisionTreeRegressor

### Task: 9: Train a Bagging Classifier

In [25]:
bag_cls = BaggingClassifier(random_state=42)

In [28]:
# model training
bag_cls.fit(X_train_cls,y_train_cls)

BaggingClassifier(random_state=42)

### Task 10: Train a Bagging Regressor

In [30]:
bag_reg = BaggingRegressor(random_state=42)

In [31]:
# model training
bag_reg.fit(X_train_reg,y_train_reg)

BaggingRegressor(random_state=42)

### Task 11: Compare bagging results with a single base model

In [49]:
# creating model with parameters to prevent overfitting
tree_reg = DecisionTreeRegressor(max_depth=5, min_samples_split=2, random_state=42)
tree_cls = DecisionTreeClassifier(max_depth=5, min_samples_split=2, random_state=42)

In [50]:
# training regression model
tree_reg.fit(X_train_reg,y_train_reg)

DecisionTreeRegressor(max_depth=5, random_state=42)

In [51]:
# training classification model
tree_cls.fit(X_train_cls,y_train_cls)

DecisionTreeClassifier(max_depth=5, random_state=42)

In [52]:
# Regressor model
bag_pred_reg = bag_reg.predict(X_test_reg)
tree_pred_reg = tree_reg.predict(X_test_reg)

In [53]:
# Classification model
bag_pred_cls = bag_cls.predict(X_test_cls)
tree_pred_cls = tree_cls.predict(X_test_cls)

In [54]:
from sklearn.metrics import accuracy_score,r2_score

In [55]:
pd.DataFrame({
    'R2 Score': [r2_score(y_test_reg,tree_pred_reg),r2_score(y_test_reg,bag_pred_reg)],
    'Accuracy Score': [r2_score(y_test_cls,tree_pred_cls),r2_score(y_test_cls,bag_pred_cls)]
},index=['Decision Tree','Bagging Model'])

               R2 Score  Accuracy Score
Decision Tree  0.998326             1.0
Bagging Model  0.999979             1.0